/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('reviews').del()
  await knex('reviews').insert([
    {product_id: 11, user_id: 1, comment: "null", rating: 5},
    {product_id: 11, user_id: 1, comment: null, rating: 5},
    {product_id: 11, user_id: 1, comment: "", rating: 5},
    {product_id: 11, user_id: 2, comment: "\n\n\n   \n", rating: 5},
    {product_id: 11, user_id: 2, comment: "   \n   \n\n", rating: 5},
    {product_id: 11, user_id: 2, comment: "this is good shit, i've never seen anything like this", rating: 5},
    {product_id: 11, user_id: 2, comment: "oh can't you see? West Virginia!!! O Im just kidding, i want ot see sth cool and spended some moeny buying this greate peace of shyt", rating: 5},
    {product_id: 11, user_id: 1, comment: "Lorem ipsum odor amet, consectetuer adipiscing elit. Facilisis duis et velit magna inceptos dignissim praesent. Lobortis neque hendrerit maximus iaculis erat sem feugiat massa. Pharetra at aenean diam potenti rutrum penatibus sodales porta. Litora ante dictumst sodales efficitur in feugiat nibh neque conubia. Vulputate condimentum congue tortor justo primis massa penatibus elementum amet. Integer volutpat suspendisse porttitor morbi natoque montes at penatibus. Integer nec ut eu integer habitant ipsum porta parturient nisi.\nHimenaeos nullam natoque ut donec dis maximus consequat. Vulputate scelerisque aliquam ante massa aenean vitae. Curabitur odio potenti duis tellus orci praesent. Donec purus velit vulputate, gravida elementum habitasse. Lobortis est facilisi vehicula phasellus a hac viverra primis? Sed finibus justo augue fusce nostra mi. Potenti dignissim tempus parturient duis lacinia per eget. Dis lacus fames sem malesuada nascetur nulla id congue. Ridiculus volutpat dolor vel sed aenean odio senectus.", rating: 5},
    {product_id: 11, user_id: 1, comment: null, rating: 5},
    {product_id: 11, user_id: 1, comment: null, rating: 4},
    {product_id: 11, user_id: 2, comment: null, rating: 2},
    {product_id: 11, user_id: 1, comment: null, rating: 3},
    {product_id: 11, user_id: 2, comment: "Lorecurabitur. Eu suspendisse dui interdum dui; nec ipsum himenaeos si.Sit vestibulum lacinia curae sodales quam felis taciti.Lorecurabitur. Eu suspendisse dui interdum dui; nec ipsum himenaeos si.Sit vestibulum lacinia curae sodales quam felis taciti.Lorecurabitur. Eu suspendisse dui interdum dui; nec ipsum himenaeos si.Sit vestibulum lacinia curae sodales quam felis taciti.Lorecurabitur. Eu suspendisse dui interdum dui; nec ipsum himenaeos si.Sit vestibulum lacinia curae sodales quam felis taciti.Lorecurabitur. Eu suspendisse dui interdum dui; nec ipsum himenaeos si.Sit vestibulum lacinia curae sodales quam felis taciti.Lorecurabitur. Eu suspendisse dui interdum dui; nec ipsum himenaeos si.Sit vestibulum lacinia curae sodales quam felis taciti.Lorecurabitur. Eu suspendisse dui interdum dui; nec ipsum himenaeos si.Sit vestibulum lacinia curae sodales quam felis taciti.Lorecurabitur. Eu suspendisse dui interdum dui; nec ipsum himenaeos si.Sit vestibulum lacinia curae sodales quam felis taciti.Lorecurabitur. Eu suspendisse dui interdum dui; nec ipsum himenaeos si.Sit vestibulum lacinia curae sodales quam felis taciti.Lorecurabitur. Eu suspendisse dui interdum dui; nec ipsum himenaeos si.Sit vestibulum lacinia curae sodales quam felis taciti.Lorecurabitur. Eu suspendisse dui interdum dui; nec ipsum himenaeos si.Sit vestibulum lacinia curae sodales quam felis taciti.Lorecurabitur. Eu suspendisse dui interdum dui; nec ipsum himenaeos si.Sit vestibulum lacinia curae sodales quam felis taciti.Lorecurabitur. Eu suspendisse dui interdum dui; nec ipsum himenaeos si.Sit vestibulum lacinia curae sodales quam felis taciti.Lorecurabitur. Eu suspendisse dui interdum dui; nec ipsum himenaeos si.Sit vestibulum lacinia curae sodales quam felis taciti.Lorecurabitur. Eu suspendisse dui interdum dui; nec ipsum himenaeos si.Sit vestibulum lacinia curae sodales quam felis taciti.Lorecurabitur. Eu suspendisse dui interdum dui; nec ipsum himenaeos si.Sit vestibulum lacinia curae sodales quam felis taciti.Lorecurabitur. Eu suspendisse dui interdum dui; nec ipsum himenaeos si.Sit vestibulum lacinia curae sodales quam felis taciti.Lorecurabitur. Eu suspendisse dui interdum dui; nec ipsum himenaeos si.Sit vestibulum lacinia curae sodales quam felis taciti.Lorecurabitur. Eu suspendisse dui interdum dui; nec ipsum himenaeos si.Sit vestibulum lacinia curae sodales quam felis taciti.", rating: 1},
    {product_id: 11, user_id: 2, comment: null, rating: 1},
    {product_id: 11, user_id: 1, comment: null, rating: 5},
    {product_id: 11, user_id: 2, comment: "Lorem ipsum odor amet, consectetuer adipiscing elit. Nunc sollicitudin accumsan nostra molestie conubia fermentum laoreet inceptos urna.Lorem ipsum odor amet, consectetuer adipiscing elit. Nunc sollicitudin accumsan nostra molestie conubia fermentum laoreet inceptos urna.", rating: 3},
    {product_id: 11, user_id: 2, comment: null, rating: 5},
    {product_id: 11, user_id: 1, comment: null, rating: 5},
    {product_id: 11, user_id: 1, comment: "Lorem ipsum odor amet, consectetuer adipiscing elit. Suscipit habitasse diam nulla; amet blandit maximus. Porttitor aptent pharetra est elit dis taciti hendrerit sagittis. Nunc volutpat tristique ligula elit aliquet aliquam vehicula. Ligula urna ultrices ad convallis magnis lacus mauris eu. Nam a litora facilisis potenti aenean est? Ex feugiat sodales parturient fermentum dictum ex aptent. Ut rhoncus sit duis est laoreet eget. Parturient nisl sodales mi pretium luctus nullam eget maximus. Enim dui aptent habitasse eget imperdiet hendrerit fringilla eros penatibus. Fusce pulvinar justo vehicula platea fusce.", rating: 3},
    {product_id: 11, user_id: 1, comment: null, rating: 4},
    {product_id: 11, user_id: 1, comment: "null", rating: 2},
    {product_id: 11, user_id: 2, comment: "Lorem ipsum odor amet, consectetuer adipiscing elit. Nunc sollicitudin accumsan nostra molestie conubia fermentum laoreet inceptos urna.", rating: 2},
    {product_id: 11, user_id: 2, comment: "Lorem ipsum odor amet, consectetuer adipiscing elit. Suscipit habitasse diam nulla; amet blandit maximus. Porttitor aptent pharetra est elit dis taciti hendrerit sagittis. Nunc volutpat tristique ligula elit aliquet aliquam vehicula. Ligula urna ultrices ad convallis magnis lacus mauris eu. Nam a litora facilisis potenti aenean est? Ex feugiat sodales parturient fermentum dictum ex aptent. Ut rhoncus sit duis est laoreet eget. Parturient nisl sodales mi pretium luctus nullam eget maximus. Enim dui aptent habitasse eget imperdiet hendrerit fringilla eros penatibus. Fusce pulvinar justo vehicula platea fusce.", rating: 1},
    {product_id: 11, user_id: 2, comment: "Lorem ipsum odor amet, consectetuer adipiscing elit. Potenti facilisis ad vel, sem nunc elementum. Suscipit iaculis tempus phasellus congue platea inceptos. Quam commodo praesent nibh integer orci. Aenean condimentum molestie, eget adipiscing ante himenaeos neque venenatis? Sit fusce purus eros proin metus ipsum molestie tempus neque. Ullamcorper eleifend felis elementum at habitant imperdiet natoque imperdiet. Orci ornare per consectetur felis nam. Venenatis vitae dapibus bibendum parturient malesuada. Habitant habitant inceptos odio tristique rhoncus dignissim. Nascetur ridiculus et leo justo torquent id felis dui auctor. Nascetur sem mus eget; vitae commodo pretium. Taciti fermentum fusce mollis sed quam auctor laoreet. Dictum sit nisl eleifend dictumst eget velit quis justo auctor. Velit venenatis dictumst natoque, massa himenaeos in vel dui. Iaculis nisl tempus tellus eros potenti enim consequat. Aptent commodo eu non mi lacus tristique. Condimentum neque viverra velit sapien parturient. Primis risus feugiat proin tellus parturient ante. Nulla elementum varius sollicitudin dolor et eu molestie id. Mattis platea maximus suspendisse venenatis quis convallis ultrices. Ut vehicula justo cras pharetra tortor posuere interdum. Finibus consectetur class velit in porta feugiat massa scelerisque. Lobortis orci morbi turpis ipsum, ligula venenatis maximus orci accumsan.", rating: 2},
    {product_id: 11, user_id: 1, comment: null, rating: 2},
    {product_id: 11, user_id: 1, comment: null, rating: 1},
    {product_id: 11, user_id: 1, comment: "Lorem ipsum odor amet, consectetuer adipiscing elit. Iaculis magnis ex penatibus tempus hac primis ac. Ataciti scelerisque litora donec rutrum et cras tortor. Quisque semper pellentesque turpis habitasse primis turpis semper. Faucibus nostra tempus habitant lacinia elit; aliquam vivamus elit.", rating: 3},
    {product_id: 11, user_id: 1, comment: "Lorecurabitur. Eu suspendisse dui interdum dui; nec ipsum himenaeos si.Sit vestibulum lacinia curae sodales quam felis taciti.Lorecurabitur. Eu suspendisse dui interdum dui; nec ipsum himenaeos si.Sit vestibulum lacinia curae sodales quam felis taciti.Lorecurabitur. Eu suspendisse dui interdum dui; nec ipsum himenaeos si.Sit vestibulum lacinia curae sodales quam felis taciti.Lorecurabitur. Eu suspendisse dui interdum dui; nec ipsum himenaeos si.Sit vestibulum lacinia curae sodales quam felis taciti", rating: 3},


  ]);
};
